version: "3"
services:
  app:
    container_name: domain_event
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./domain_event:/app/domain_event
    working_dir: /app/domain_event
    environment:
      - PYTHONPATH=/app
    tty: true
